name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the feature
      placeholder: What do you want to add or improve?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve? Why is it needed?
      placeholder: |
        Currently, I have to...
        This is frustrating because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package would this affect?
      options:
        - web (frontend)
        - api (backend)
        - ui (shared components)
        - config (shared config)
        - types (shared types)
        - docs
        - Multiple packages
        - New package
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Suggested Priority
      description: How important is this feature?
      options:
        - P1 - Critical (blocking work)
        - P2 - High (needed soon)
        - P3 - Medium (nice to have)
    validations:
      required: false

  - type: dropdown
    id: size
    attributes:
      label: Estimated Size
      description: How complex do you think this is?
      options:
        - XS - Trivial
        - S - Small
        - M - Medium
        - L - Large
        - XL - Epic (needs breakdown)
        - Not sure
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've thought about?
      placeholder: Other approaches that could work
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: Links, screenshots, code examples, etc.
    validations:
      required: false
