export const ErrorCode = {
  // RBAC
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_SLUG_CONFLICT: 'ROLE_SLUG_CONFLICT',
  DEFAULT_ROLE_CONSTRAINT: 'DEFAULT_ROLE_CONSTRAINT',
  OWNERSHIP_CONSTRAINT: 'OWNERSHIP_CONSTRAINT',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  // Tenant
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_SCHEDULED_FOR_DELETION: 'ACCOUNT_SCHEDULED_FOR_DELETION',
  EMAIL_CONFIRMATION_MISMATCH: 'EMAIL_CONFIRMATION_MISMATCH',
  // Organization
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  ORG_SCHEDULED_FOR_DELETION: 'ORG_SCHEDULED_FOR_DELETION',
  ORG_NOT_DELETED: 'ORG_NOT_DELETED',
  ORG_NAME_CONFIRMATION_MISMATCH: 'ORG_NAME_CONFIRMATION_MISMATCH',
  ORG_NOT_OWNER: 'ORG_NOT_OWNER',
  TRANSFER_TARGET_NOT_MEMBER: 'TRANSFER_TARGET_NOT_MEMBER',
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
