export const ErrorCode = {
  // RBAC
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_SLUG_CONFLICT: 'ROLE_SLUG_CONFLICT',
  DEFAULT_ROLE_CONSTRAINT: 'DEFAULT_ROLE_CONSTRAINT',
  OWNERSHIP_CONSTRAINT: 'OWNERSHIP_CONSTRAINT',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  // Tenant
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  // Consent
  CONSENT_NOT_FOUND: 'CONSENT_NOT_FOUND',
  CONSENT_INSERT_FAILED: 'CONSENT_INSERT_FAILED',
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
